<?php

require_once('nd_genotypes.admin.inc');
require_once('nd_genotypes.form_elements.inc');
require_once('nd_genotypes.genotype_summary.inc');

// Mviews
include_once('mviews/nd_genotype_experiment.inc');
include_once('mviews/nd_genotype_polymorphism.inc');
include_once('mviews/nd_genotype_experiment_summary.inc');

// Views data export
include_once('views_data_export/nd_genotypes.views_data_export.inc');

/**
 * Implements hook_views_api()
 *
 * Purpose: Essentially this hook tells drupal that there is views support for
 *  for this module which then includes kp_genotypes.views.inc where all the
 *  views integration code is
 *
 * @return
 *   An array with fields important for views integration
 *
 */ 
function nd_genotypes_views_api() {
   return array(
      'api' => 2.0,
   );
}

/**
 * Register any menu items for this module
 */
function nd_genotypes_menu () {
	$items = array();
	
	$items['admin/tripal/nd_genotypes'] = array(
    'page callback' => 'nd_genotypes_admin_description',
    'title' => 'ND Genotypes',
    'access arguments' => array('administer site configuration'),
  );

  $items['admin/tripal/nd_genotypes/configuration'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nd_genotypes_configuration_form'),
    'title' => 'Configuration',
    'access arguments' => array('administer site configuration'),
  );
 
   $items['genotypes/summary'] = array(
    'page callback' => 'nd_genotypes_genotype_summary_page',
    'title' => 'Genotype Summary',
    'access arguments' => array('access content'),
  );
   
	return $items;
}

/**
 * Register any theme functions/templates for this module
 */
function nd_genotypes_theme () {
  return nd_genotypes_form_element_theme();
}