<?php
/**
 *
 */

/**
 * Implements hook_install().
 */
function nd_genotypes_enable() {

  // Determine the PostgreSQL version.
  nd_genotypes_recheck_postgresql_version();

  // Ensure we have the vocab terms we would like to use as defaults.
  tripal_insert_cv(
    'MIXSCV',
    'Controlled vocabularies for the MIxS family of metadata checklists. See http://gensc.org/gc_wiki/index.php/MIxS for details on the MIxS checklists.'
  );
  tripal_insert_cvterm(array(
    'id' => 'MVC:0000491',
    'name' => 'extracted',
    'cv_name' => 'MIXSCV',
    'definition' => 'A material separation in which a desired component (the subject) of an input material (the object) is separated from the remainder',
  ));

  tripal_insert_cvterm(array(
    'id' => 'RO:0002607',
    'name' => 'is marker for',
    'cv_name' => 'relationship',
    'definition' => 'c is marker for d iff the presence or occurrence of d is correlated with the presence of occurrence of c, and the observation of c is used to infer the presence or occurrence of d. Note that this does not imply that c and d are in a direct causal relationship, as it may be the case that there is a third entity e that stands in a direct causal relationship with c and d.',
  ));

  tripal_insert_cvterm(array(
    'id' => 'local:count',
    'name' => 'count',
    'cv_name' => 'local',
    'definition' => 'An integer indicating the number of something in a generic sense.',
  ));
}

/**
 * Implements hook_install().
 */
function nd_genotypes_install() {

  // Determine the PostgreSQL version.
  nd_genotypes_recheck_postgresql_version();

  // Create the genotype_call table for storing genotypes in chado.
  chado_create_custom_table(
    'genotype_call',
    nd_genotypes_genotype_call_schema_template()
  );

  // Move our module up in the list priority-wise
  // so our templates can override default tripal ones.
  // First grab the weight of tripal_core.
  $tripal_weight = db_query('SELECT weight FROM {system} WHERE name = :name',
    array(':name' => 'tripal_core'))->fetchField();

  // Next, update our weight to be one heavier, so it moves lower in the execution order.
  db_query('UPDATE {system} SET weight = :weight WHERE name = :name',
     array(':name' => 'nd_genotypes', ':weight' => $tripal_weight + 1));

  // Give them some guidance!
  drupal_set_message('In order to see the genotype and sequence pane on feature nodes, you have to set the type(s) used for variants and markers in the module settings. Click the configure link beside the module name.','warning');
}

/**
 * Implements hook_schema().
 */
function nd_genotypes_schema() {
  $schema = array();

  $schema['ndg_matrix_variant_user_lists'] = array(
    'description' => 'Stores user entered variant name lists for use the the genotype matrix.',
    'fields' => array(
      'list_id' => array(
        'description' => 'The primary identifier for variant name list.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE
      ),
      'list' => array(
        'description' => 'An array of variant names.',
        'pgsql_type' => 'json',
        'not null' => TRUE,
      ),
      'created' => array(
        'description' => 'The date this list was first entered.',
        'type' => 'varchar',
        'pgsql_type' => 'date',
      ),
      'num_accessed' => array(
        'description' => 'The number of times this list was accessed.',
        'type' => 'int',
        'default' => 1
      ),
    ),
    'indexes' => array( ),
    'unique keys' => array( ),
    'primary key' => array('list_id'),
  );

  return $schema;
}
