<?php

// API
require_once 'api/nd_genotypes.api.inc';

// Includes
require_once 'includes/nd_genotypes.admin.inc';
require_once 'includes/nd_genotypes.form_elements.inc';
require_once 'includes/nd_genotypes.bulk_loader_template.inc';
require_once 'includes/mviews/nd_genotype_experiment.inc';
require_once 'includes/mviews/nd_genotype_germplasm.inc';

// Theme
require_once 'theme/nd_genotypes.theme.inc';

/**
 * Implements hook_views_api()
 *
 * Purpose: Essentially this hook tells drupal that there is views support for
 *  for this module which then includes kp_genotypes.views.inc where all the
 *  views integration code is
 *
 * @return
 *   An array with fields important for views integration
 *
 */
function nd_genotypes_views_api() {

  $path = drupal_get_path('module', 'nd_genotypes');

  return array(
    'api' => 3,
    'path' => $path . '/includes/views',
    'template path' => $path . '/theme/templates',
  );
}

/**
 * Register any menu items for this module
 */
function nd_genotypes_menu () {
	$items = array();

	$items['admin/tripal/extension/nd_genotypes'] = array(
    'title' => 'Natural Diversity Genotypes',
    'description' => 'Provides an interface for genotypes and the experiments that generate them.',
    'access arguments' => array('administer tripal'),
    'page callback' => 'nd_genotypes_admin_landing_page'
  );

  $items['admin/tripal/extension/nd_genotypes/sync'] = array(
    'title' => 'Sync',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nd_genotypes_admin_sync_mviews'),
    'access arguments' => array('administer tripal'),
    'weight' => 2
  );

  $items['admin/tripal/extension/nd_genotypes/settings'] = array(
    'title' => 'Settings',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nd_genotypes_admin_settings'),
    'access arguments' => array('administer tripal'),
    'weight' => 3
  );

  $items['admin/tripal/extension/nd_genotypes/help'] = array(
    'title' => 'Help',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'theme',
    'page arguments' => array('nd_genotypes__help'),
    'access arguments' => array('administer tripal'),
    'weight' => 4
  );

  // Name autocomplete (display only the preferred organism -in path).
  $items['tripal_ajax/nd_genotypes/genotyped_germplasm/name_to_id/%/only'] = array(
    'page callback' => 'nd_genotypes_germplasm_name_to_id_callback',
    'page arguments' => array(4, FALSE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  // Name autocomplete (display all organisms).
  $items['tripal_ajax/nd_genotypes/genotyped_germplasm/name_to_id/%/all'] = array(
    'page callback' => 'nd_genotypes_germplasm_name_to_id_callback',
    'page arguments' => array(4, TRUE),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );

  // Add Marker x Germplasm Matrix links (1/organism synced)
  $sql = "
    SELECT *
    FROM public.chado_organism CO
      INNER JOIN {organism} O ON O.organism_id = CO.organism_id
    ORDER BY O.genus, O.species
  ";
  $orgs = chado_query($sql);
  foreach ($orgs as $organism) {
    $items['chado/genotype/' . $organism->genus] = array(
      'title' => $organism->genus . ' Genotypes',
      'description' => 'Marker by Germplasm Genotypes Search for ' . $organism->genus . ' species.',
      'page callback' => 'views_page',
      'page arguments' => array('nd_genotypes_genotype_matrix', 'page', $organism->genus),
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
    );
  }

	return $items;
}

/**
 * Register any theme functions/templates for this module.
 */
function nd_genotypes_theme($existing, $type, $theme, $path) {
  $items = array();

  // Help Page
  $items['nd_genotypes__help'] = array(
    'template' => 'nd_genotypes--help',
    'path' => "$path/theme/templates",
  );

  // Features: Genotype pane
  $items['nd_genotypes_feature_genotypes'] = array(
    'variables' => array('node' => NULL),
    'template' => 'nd_genotypes_feature_genotypes',
    'path' => "$path/theme/templates",
  );

  // Features: Marked-up sequence pane
  $items['nd_genotypes_feature_sequence'] = array(
    'variables' => array('node' => NULL),
    'template' => 'nd_genotypes_feature_sequence',
    'path' => "$path/theme/templates",
  );

  return $items;
}

/**
 * Implements hook_node_view(). Acts on all content types.
 */
function nd_genotypes_node_view($node, $view_mode, $langcode) {
  switch ($node->type) {
    case 'chado_feature':
      if ($view_mode == 'full') {
        // the tripal_natural_diversity module provides a tripal_feature_nd_genotype
        // template. if the tripal_natural_diversity content is present get rid of it as this
        // module superceeds it.
        if (array_key_exists('tripal_feature_nd_genotypes', $node->content)) {
          unset($node->content['tripal_feature_nd_genotypes']);
        }
        if (array_key_exists('tripal_feature_seqence', $node->content)) {
          unset($node->content['tripal_feature_seqence']);
        }
        $node->content['nd_genotypes_feature_genotypes'] = array(
          '#theme' => 'nd_genotypes_feature_genotypes',
          '#node' => $node,
          '#tripal_toc_id'    => 'genotypes',
          '#tripal_toc_title' => 'Genotypes',
        );
        // Sequence mark-up page
        $node->content['nd_genotypes_feature_sequence'] = array(
          '#theme' => 'nd_genotypes_feature_sequence',
          '#node' => $node,
          '#tripal_toc_id'    => 'sequence',
          '#tripal_toc_title' => 'Sequence',
        );
      }
      break;
  }
}
